# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b4d7887aff771ef02b26f0c247c5091dddfb69caa5ecaefcbe3dfe7ffc16656d5cb824d26e98baa933883432c0af779349c5a9a6d5759764196a97e6f885ccc9

test:
  secret_key_base: 9dbe6f110b04ca6207a869e1adf491498762f8d623faeba0f22ea968a9eafb26f29d6870f641bbdcfb53296b1e9a036122c2358864a12c2cfe5e74703eaede58

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
